/* The following code was generated by JFlex 1.6.1 */

package Pascal.Parser;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Lexico.flex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int TAG = 2;
  public static final int ATTR = 4;
  public static final int DOC = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1,  1,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\11\1\16\1\16\1\15\22\0\1\5\1\0\1\13"+
    "\1\22\1\21\1\35\1\0\1\10\1\27\1\30\1\20\1\23\1\26"+
    "\1\33\1\3\1\34\12\2\1\25\1\24\1\43\1\52\1\44\2\0"+
    "\1\46\1\64\1\56\1\54\1\42\1\45\1\60\1\66\1\63\2\6"+
    "\1\47\1\61\1\53\1\55\1\57\1\6\1\40\1\51\1\37\1\41"+
    "\1\70\1\65\1\6\1\67\1\6\1\31\1\12\1\32\1\36\1\7"+
    "\1\0\1\46\1\64\1\56\1\54\1\42\1\45\1\60\1\66\1\63"+
    "\2\6\1\47\1\61\1\53\1\55\1\57\1\6\1\40\1\51\1\37"+
    "\1\41\1\70\1\65\1\6\1\67\1\6\1\14\1\4\1\17\7\0"+
    "\1\16\252\0\2\62\115\0\1\50\u1ea8\0\1\16\1\16\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\2\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\3\5\1\24"+
    "\1\25\2\5\1\1\1\5\1\26\4\5\1\1\4\5"+
    "\2\0\1\27\3\0\1\30\3\0\4\5\1\31\1\32"+
    "\1\33\3\5\1\0\3\5\1\0\1\5\1\34\1\35"+
    "\3\5\1\0\6\5\1\36\1\27\1\30\2\2\4\0"+
    "\3\5\1\37\2\5\1\40\1\0\2\5\1\41\1\42"+
    "\2\43\3\5\1\0\3\5\1\0\2\5\1\44\2\0"+
    "\1\2\1\0\1\45\1\46\1\47\1\0\2\5\1\0"+
    "\1\5\1\50\1\0\1\5\1\27\1\5\1\0\1\5"+
    "\1\0\2\5\1\0\1\5\1\51\1\0\3\2\2\52"+
    "\1\53\1\0\1\5\2\54\2\5\1\0\1\5\2\55"+
    "\1\5\2\56\1\2\1\0\2\57\1\60\1\5\1\0"+
    "\2\5\1\0\1\5\1\61\2\62\1\63\2\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\71\0\162\0\253\0\71\0\344\0\u011d"+
    "\0\71\0\u0156\0\u018f\0\71\0\71\0\71\0\71\0\71"+
    "\0\71\0\71\0\71\0\71\0\71\0\71\0\71\0\71"+
    "\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e\0\u0357"+
    "\0\u0390\0\71\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6"+
    "\0\u051f\0\u0558\0\u0591\0\u05ca\0\u011d\0\71\0\u0603\0\u0156"+
    "\0\u063c\0\71\0\u0675\0\u06ae\0\u06e7\0\u0720\0\u0759\0\u0792"+
    "\0\u07cb\0\71\0\71\0\71\0\u0804\0\u083d\0\u0876\0\u08af"+
    "\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc\0\344\0\344\0\u0a05"+
    "\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd"+
    "\0\u0c06\0\u05ca\0\u011d\0\u0156\0\71\0\u0c3f\0\u0c78\0\u0cb1"+
    "\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\344\0\u0e07\0\u0e40"+
    "\0\344\0\u0e79\0\u0eb2\0\u0eeb\0\344\0\344\0\71\0\344"+
    "\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041\0\u107a\0\u10b3"+
    "\0\u10ec\0\u1125\0\344\0\u115e\0\u1197\0\u11d0\0\u1209\0\344"+
    "\0\344\0\344\0\u1242\0\u127b\0\u12b4\0\u12ed\0\u1326\0\344"+
    "\0\u135f\0\u1398\0\u13d1\0\u140a\0\u1443\0\u147c\0\u14b5\0\u14ee"+
    "\0\u1527\0\u1560\0\u1599\0\344\0\u15d2\0\u0cb1\0\u160b\0\u0cea"+
    "\0\71\0\344\0\344\0\u1644\0\u167d\0\71\0\344\0\u16b6"+
    "\0\u16ef\0\u1728\0\u1761\0\71\0\344\0\u179a\0\u17d3\0\u180c"+
    "\0\u1197\0\u1845\0\71\0\344\0\344\0\u187e\0\u18b7\0\u18f0"+
    "\0\u1929\0\u1962\0\u199b\0\344\0\71\0\344\0\344\0\71"+
    "\0\344";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\3\1\4\1\7\1\3"+
    "\1\10\1\11\1\3\1\12\1\13\1\4\1\0\1\3"+
    "\1\14\2\3\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\7\1\33\1\34\1\35\1\36\1\37\1\7\1\40"+
    "\1\41\1\42\1\43\1\7\1\44\1\45\1\46\2\7"+
    "\1\47\1\50\1\51\1\52\2\7\1\53\72\0\1\4"+
    "\3\0\1\4\7\0\1\4\55\0\1\5\1\54\67\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\6\7\10\55"+
    "\1\56\1\0\1\57\56\55\11\60\1\0\1\61\1\62"+
    "\55\60\11\63\1\0\3\63\2\0\1\64\1\65\50\63"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\1\7"+
    "\1\66\2\7\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\4\7\1\67\1\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\3\7\1\70\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\0\6\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\71\6\7\1\0\6\7\44\0\1\72"+
    "\5\0\1\73\70\0\1\74\20\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\1\7\1\75\1\7"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\1\7\1\76\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\77\6\7\1\0"+
    "\6\7\37\0\1\100\33\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\1\101\3\7\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\1\7\1\102\1\7"+
    "\1\0\1\7\1\0\2\7\1\103\4\7\1\104\1\105"+
    "\5\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\1\7\1\106\2\7\2\0\1\107\2\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\2\7\1\110\4\7\1\0\3\7\1\111\2\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\1\7"+
    "\1\112\2\7\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\6\7\53\0\1\113\17\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\114\6\7\1\0\6\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\3\7\1\115\2\0\3\7"+
    "\1\0\1\7\1\0\2\7\1\116\4\7\1\0\6\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\1\7"+
    "\1\117\2\7\2\0\3\7\1\0\1\7\1\0\2\7"+
    "\1\120\4\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\1\7\1\121\1\7"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\2\0\1\122"+
    "\1\0\2\122\63\0\10\55\1\123\1\0\1\57\56\55"+
    "\11\60\1\0\1\61\1\124\55\60\11\63\1\0\3\63"+
    "\2\0\1\64\62\63\1\125\3\63\1\126\1\0\1\64"+
    "\51\63\11\127\1\130\2\127\1\65\2\130\1\131\1\132"+
    "\1\63\47\127\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\2\7\1\133\1\7\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\4\7\1\134\2\7\1\0\6\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\1\7"+
    "\1\135\1\7\1\0\1\7\1\0\7\7\1\0\6\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\1\136\5\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\2\7\1\137\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\1\7\1\140\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\0\6\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\1\141\5\7\1\0\6\7\40\0"+
    "\1\142\32\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\1\7\1\143\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\144\6\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\1\145\1\146\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\47\0\1\147"+
    "\23\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\2\7\1\150\1\0\1\7\1\0\7\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\1\151\6\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\1\7\1\152\1\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\2\7\1\153\4\7\1\0\6\7\37\0\1\154"+
    "\33\0\1\7\3\0\2\7\23\0\1\7\3\0\1\155"+
    "\3\7\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\5\7\1\156"+
    "\1\7\1\0\6\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\0\1\7\1\0"+
    "\2\7\1\157\4\7\1\0\6\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\160\1\161\5\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\1\7\1\162\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\0\6\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\1\7"+
    "\1\163\2\7\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\6\7\11\0\1\125\57\0\11\63\1\0\2\63"+
    "\1\164\2\0\1\64\51\63\14\0\1\165\54\0\11\63"+
    "\1\125\2\63\1\164\1\126\1\0\1\64\51\63\11\164"+
    "\1\165\3\164\2\165\1\166\1\167\1\164\1\63\46\164"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\3\7"+
    "\1\170\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\3\7\1\171\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\2\7\1\172\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\173\1\174\1\0"+
    "\7\7\1\0\6\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\1\7\1\175\1\7\1\0"+
    "\1\7\1\0\7\7\1\0\6\7\62\0\2\176\7\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\176\1\177\5\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\1\200\5\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\3\7\1\201\1\202\1\0\7\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\1\7\1\203\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\5\7\1\204\1\7\1\0\6\7\42\0\1\205"+
    "\30\0\1\7\3\0\2\7\23\0\1\7\3\0\3\7"+
    "\1\206\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\7\7\1\207"+
    "\1\210\5\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\2\7\1\211\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\37\0\1\212\33\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\1\213\3\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\7\1\214\5\7\1\0\6\7"+
    "\11\127\1\130\3\127\2\130\1\131\1\132\1\63\47\127"+
    "\20\130\1\215\1\0\47\130\11\127\1\216\3\127\1\217"+
    "\1\130\1\131\1\132\1\63\60\127\1\130\3\127\2\130"+
    "\1\220\1\132\1\63\47\127\42\0\1\221\30\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\3\7\1\222\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\6\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\4\7\1\223"+
    "\1\7\53\0\1\224\17\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\225\6\7\1\0\6\7\37\0\1\226\33\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\1\227\3\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\6\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\1\7\1\230\1\7\1\0\1\7\1\0\7\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\1\7\1\231\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\60\0\1\232\12\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\5\7\1\233\1\7\1\0\6\7\53\0"+
    "\1\234\17\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\1\235\6\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\3\7\1\236\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\42\0\1\237\30\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\3\7\1\240\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\17\165\1\241"+
    "\1\242\1\165\1\0\46\165\11\0\1\125\2\0\1\165"+
    "\134\0\1\243\12\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\3\7\1\0\1\7\1\0\5\7"+
    "\1\244\1\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\1\245\3\7\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\0\6\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\1\7\1\246"+
    "\1\7\1\0\1\7\1\0\7\7\1\0\6\7\42\0"+
    "\1\247\30\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\3\7\1\250\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\1\7\1\251\1\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\47\0\1\252\23\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\2\7"+
    "\1\253\1\0\1\7\1\0\7\7\1\0\6\7\17\130"+
    "\1\216\1\215\1\0\47\130\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\6\7\1\254\1\0\6\7\40\0\1\255\32\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\1\7\1\256"+
    "\2\7\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\1\257\6\7"+
    "\1\0\6\7\53\0\1\260\17\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\261\6\7\1\0\6\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6612];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\1\11\2\1\1\11\2\1\1\11\2\1"+
    "\15\11\11\1\1\11\11\1\2\0\1\11\3\0\1\11"+
    "\3\0\4\1\3\11\3\1\1\0\3\1\1\0\6\1"+
    "\1\0\11\1\1\11\1\1\4\0\7\1\1\0\4\1"+
    "\1\11\4\1\1\0\3\1\1\0\3\1\2\0\1\1"+
    "\1\0\3\1\1\0\2\1\1\0\2\1\1\0\3\1"+
    "\1\0\1\1\1\0\2\1\1\0\2\1\1\0\3\1"+
    "\1\11\2\1\1\0\1\1\1\11\3\1\1\0\1\1"+
    "\1\11\5\1\1\0\1\11\3\1\1\0\2\1\1\0"+
    "\2\1\1\11\2\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
  	yyline=1;
	yychar=1;
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 230) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.println("Este es un error lexico: "+yytext()+", en la linea: "+yyline+", en la columna: "+yychar);
            }
          case 53: break;
          case 2: 
            { 
            }
          case 54: break;
          case 3: 
            { return new Symbol(sym.ENTERO,yyline,yychar, yytext());
            }
          case 55: break;
          case 4: 
            { return new Symbol(sym.PNT,yyline,yychar, yytext());
            }
          case 56: break;
          case 5: 
            { return new Symbol(sym.ID,yyline,yychar, yytext());
            }
          case 57: break;
          case 6: 
            { yychar=1;
            }
          case 58: break;
          case 7: 
            { return new Symbol(sym.POR,yyline,yychar, yytext());
            }
          case 59: break;
          case 8: 
            { return new Symbol(sym.MAS,yyline,yychar, yytext());
            }
          case 60: break;
          case 9: 
            { return new Symbol(sym.PNTCOMA,yyline,yychar, yytext());
            }
          case 61: break;
          case 10: 
            { return new Symbol(sym.DSPUNTOS,yyline,yychar, yytext());
            }
          case 62: break;
          case 11: 
            { return new Symbol(sym.COMA,yyline,yychar, yytext());
            }
          case 63: break;
          case 12: 
            { return new Symbol(sym.PARIZQ,yyline,yychar, yytext());
            }
          case 64: break;
          case 13: 
            { return new Symbol(sym.PARDER,yyline,yychar, yytext());
            }
          case 65: break;
          case 14: 
            { return new Symbol(sym.LLAVEIZQ,yyline,yychar, yytext());
            }
          case 66: break;
          case 15: 
            { return new Symbol(sym.LLAVEDER,yyline,yychar, yytext());
            }
          case 67: break;
          case 16: 
            { return new Symbol(sym.MENOS,yyline,yychar, yytext());
            }
          case 68: break;
          case 17: 
            { return new Symbol(sym.DIVIDIDO,yyline,yychar, yytext());
            }
          case 69: break;
          case 18: 
            { return new Symbol(sym.MODULO,yyline,yychar, yytext());
            }
          case 70: break;
          case 19: 
            { return new Symbol(sym.POTENCIA,yyline,yychar, yytext());
            }
          case 71: break;
          case 20: 
            { return new Symbol(sym.MENOR,yyline,yychar, yytext());
            }
          case 72: break;
          case 21: 
            { return new Symbol(sym.MAYOR,yyline,yychar, yytext());
            }
          case 73: break;
          case 22: 
            { return new Symbol(sym.IGUAL,yyline,yychar, yytext());
            }
          case 74: break;
          case 23: 
            { return new Symbol(sym.CHAR,yyline,yychar, yytext());
            }
          case 75: break;
          case 24: 
            { return new Symbol(sym.CADENA,yyline,yychar, yytext());
            }
          case 76: break;
          case 25: 
            { return new Symbol(sym.DIFERENTE,yyline,yychar, yytext());
            }
          case 77: break;
          case 26: 
            { return new Symbol(sym.MENORIGUAL,yyline,yychar, yytext());
            }
          case 78: break;
          case 27: 
            { return new Symbol(sym.MAYORIGUAL,yyline,yychar, yytext());
            }
          case 79: break;
          case 28: 
            { return new Symbol(sym.OR,yyline,yychar, yytext());
            }
          case 80: break;
          case 29: 
            { return new Symbol(sym.OF,yyline,yychar, yytext());
            }
          case 81: break;
          case 30: 
            { return new Symbol(sym.DECIMAL,yyline,yychar, yytext());
            }
          case 82: break;
          case 31: 
            { return new Symbol(sym.END,yyline,yychar, yytext());
            }
          case 83: break;
          case 32: 
            { return new Symbol(sym.AND,yyline,yychar, yytext());
            }
          case 84: break;
          case 33: 
            { return new Symbol(sym.NOT,yyline,yychar, yytext());
            }
          case 85: break;
          case 34: 
            { return new Symbol(sym.NOR,yyline,yychar, yytext());
            }
          case 86: break;
          case 35: 
            { return new Symbol(sym.NIL,yyline,yychar, yytext());
            }
          case 87: break;
          case 36: 
            { return new Symbol(sym.VAR,yyline,yychar, yytext());
            }
          case 88: break;
          case 37: 
            { return new Symbol(sym.TRUE,yyline,yychar, yytext());
            }
          case 89: break;
          case 38: 
            { return new Symbol(sym.TYPE,yyline,yychar, yytext());
            }
          case 90: break;
          case 39: 
            { return new Symbol(sym.REAL,yyline,yychar, yytext());
            }
          case 91: break;
          case 40: 
            { return new Symbol(sym.NAND,yyline,yychar, yytext());
            }
          case 92: break;
          case 41: 
            { return new Symbol(sym.WORD,yyline,yychar, yytext());
            }
          case 93: break;
          case 42: 
            { return new Symbol(sym.FALSE,yyline,yychar, yytext());
            }
          case 94: break;
          case 43: 
            { return new Symbol(sym.ARRAY,yyline,yychar, yytext());
            }
          case 95: break;
          case 44: 
            { return new Symbol(sym.CONST,yyline,yychar, yytext());
            }
          case 96: break;
          case 45: 
            { return new Symbol(sym.BEGIN,yyline,yychar, yytext());
            }
          case 97: break;
          case 46: 
            { return new Symbol(sym.WRITE,yyline,yychar, yytext());
            }
          case 98: break;
          case 47: 
            { return new Symbol(sym.STRING,yyline,yychar, yytext());
            }
          case 99: break;
          case 48: 
            { return new Symbol(sym.CHARAT,yyline,yychar, yytext());
            }
          case 100: break;
          case 49: 
            { return new Symbol(sym.PROGRAM,yyline,yychar, yytext());
            }
          case 101: break;
          case 50: 
            { return new Symbol(sym.INTEGER,yyline,yychar, yytext());
            }
          case 102: break;
          case 51: 
            { return new Symbol(sym.BOOLEAN,yyline,yychar, yytext());
            }
          case 103: break;
          case 52: 
            { return new Symbol(sym.WRITELN,yyline,yychar, yytext());
            }
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
