/* The following code was generated by JFlex 1.6.1 */

package Pascal.Parser;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Lexico.flex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int TAG = 2;
  public static final int ATTR = 4;
  public static final int DOC = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1,  1,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\11\1\16\1\16\1\15\22\0\1\5\1\0\1\13"+
    "\1\22\1\21\1\35\1\0\1\10\1\27\1\30\1\20\1\23\1\26"+
    "\1\33\1\3\1\34\12\2\1\25\1\24\1\43\1\52\1\44\2\0"+
    "\1\46\1\64\1\56\1\54\1\42\1\45\1\60\1\66\1\63\2\6"+
    "\1\47\1\61\1\53\1\55\1\57\1\6\1\40\1\51\1\37\1\41"+
    "\1\70\1\65\1\6\1\67\1\71\1\31\1\12\1\32\1\36\1\7"+
    "\1\0\1\46\1\64\1\56\1\54\1\42\1\45\1\60\1\66\1\63"+
    "\2\6\1\47\1\61\1\53\1\55\1\57\1\6\1\40\1\51\1\37"+
    "\1\41\1\70\1\65\1\6\1\67\1\71\1\14\1\4\1\17\7\0"+
    "\1\16\252\0\2\62\115\0\1\50\u1ea8\0\1\16\1\16\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\2\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\3\5\1\24"+
    "\1\25\3\5\1\1\1\5\1\26\5\5\1\1\4\5"+
    "\2\0\1\27\3\0\1\30\3\0\5\5\1\31\1\32"+
    "\1\33\4\5\2\0\4\5\1\0\1\5\1\34\1\35"+
    "\4\5\1\0\6\5\1\36\1\27\1\30\2\2\4\0"+
    "\7\5\1\37\2\5\1\40\1\5\2\0\3\5\1\41"+
    "\1\42\2\43\4\5\1\0\3\5\1\0\2\5\1\44"+
    "\2\0\1\2\1\0\1\45\2\5\1\46\1\47\2\5"+
    "\1\0\3\5\2\0\2\5\1\50\1\0\1\5\1\27"+
    "\2\5\1\0\1\5\1\0\2\5\1\0\1\5\1\51"+
    "\1\0\3\2\4\5\2\52\1\53\1\5\2\0\2\5"+
    "\2\54\3\5\1\0\1\5\2\55\1\5\2\56\1\2"+
    "\1\0\2\5\1\57\1\5\1\60\1\61\1\62\1\61"+
    "\1\62\1\63\1\5\1\64\1\0\2\5\1\0\3\5"+
    "\1\65\1\66\2\67\1\70\2\71\4\5\1\0\1\5"+
    "\1\0\1\5\2\72\2\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[231];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\72\0\164\0\256\0\72\0\350\0\u0122"+
    "\0\72\0\u015c\0\u0196\0\72\0\72\0\72\0\72\0\72"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\72\0\72"+
    "\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c\0\u0366"+
    "\0\u03a0\0\u03da\0\72\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc"+
    "\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0122\0\72"+
    "\0\u0692\0\u015c\0\u06cc\0\72\0\u0706\0\u0740\0\u077a\0\u07b4"+
    "\0\u07ee\0\u0828\0\u0862\0\u089c\0\72\0\72\0\72\0\u08d6"+
    "\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6"+
    "\0\u0ae0\0\u0b1a\0\u0b54\0\350\0\350\0\u0b8e\0\u0bc8\0\u0c02"+
    "\0\u0c3c\0\u0c76\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\u0d98\0\u0dd2"+
    "\0\u0658\0\u0122\0\u015c\0\72\0\u0e0c\0\u0e46\0\u0e80\0\u0eba"+
    "\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2\0\u0fdc\0\u1016\0\u1050\0\u108a"+
    "\0\350\0\u10c4\0\u10fe\0\350\0\u1138\0\u1172\0\u11ac\0\u11e6"+
    "\0\u1220\0\u125a\0\350\0\350\0\72\0\350\0\u1294\0\u12ce"+
    "\0\u1308\0\u1342\0\u137c\0\u13b6\0\u13f0\0\u142a\0\u1464\0\u149e"+
    "\0\u14d8\0\350\0\u1512\0\u154c\0\u1586\0\u15c0\0\350\0\u15fa"+
    "\0\u1634\0\350\0\350\0\u166e\0\u16a8\0\u16e2\0\u171c\0\u1756"+
    "\0\u1790\0\u17ca\0\u1804\0\u183e\0\u1878\0\350\0\u18b2\0\u18ec"+
    "\0\u1926\0\u1960\0\u199a\0\u19d4\0\u1a0e\0\u1a48\0\u1a82\0\u1abc"+
    "\0\u1af6\0\u1b30\0\350\0\u1b6a\0\u0e80\0\u1ba4\0\u0eba\0\u1bde"+
    "\0\u1c18\0\u1c52\0\u1c8c\0\72\0\350\0\350\0\u1cc6\0\u1d00"+
    "\0\u1d3a\0\u1d74\0\u1dae\0\72\0\350\0\u1de8\0\u1e22\0\u1e5c"+
    "\0\u1e96\0\u1ed0\0\72\0\350\0\u1f0a\0\u1f44\0\u1f7e\0\u154c"+
    "\0\u1fb8\0\u1ff2\0\u202c\0\350\0\u2066\0\350\0\72\0\72"+
    "\0\350\0\350\0\350\0\u20a0\0\350\0\u20da\0\u2114\0\u214e"+
    "\0\u2188\0\u21c2\0\u21fc\0\u2236\0\350\0\350\0\72\0\350"+
    "\0\350\0\72\0\350\0\u2270\0\u22aa\0\u22e4\0\u231e\0\u2358"+
    "\0\u2392\0\u23cc\0\u2406\0\72\0\350\0\72\0\350";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[231];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\3\1\4\1\7\1\3"+
    "\1\10\1\11\1\3\1\12\1\13\1\4\1\0\1\3"+
    "\1\14\2\3\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\7\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\7\1\45\1\46\1\47\1\7"+
    "\1\50\1\51\1\52\1\53\1\54\2\7\1\55\1\7"+
    "\73\0\1\4\3\0\1\4\7\0\1\4\56\0\1\5"+
    "\1\56\70\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\7\7\10\57\1\60\1\0\1\61\57\57\11\62\1\0"+
    "\1\63\1\64\56\62\11\65\1\0\3\65\2\0\1\66"+
    "\1\67\51\65\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\1\7\1\70\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\2\7\1\71\4\7\1\0\4\7\1\72\2\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\3\7"+
    "\1\73\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\7\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\1\74\6\7"+
    "\1\0\7\7\44\0\1\75\5\0\1\76\71\0\1\77"+
    "\21\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\1\7\1\100\1\7\1\0\1\7\1\0\7\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\1\7\1\101\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\102\6\7\1\0\7\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\3\7\1\103\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7\37\0\1\104"+
    "\22\0\2\105\10\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\1\106\3\7\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\105\1\107\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\1\7\1\110\1\7"+
    "\1\0\1\7\1\0\2\7\1\111\4\7\1\112\1\113"+
    "\6\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\1\7\1\114\2\7\2\0\1\115\2\7\1\0\1\7"+
    "\1\0\7\7\1\0\7\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\2\7\1\116\4\7\1\0\3\7\1\117\3\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\1\7"+
    "\1\120\2\7\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\1\7\1\121\1\7\1\0\1\7"+
    "\1\0\7\7\1\0\7\7\53\0\1\122\20\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\123\6\7\1\0\7\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\3\7\1\124"+
    "\2\0\3\7\1\0\1\7\1\0\2\7\1\125\4\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\1\7\1\126\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\2\7\1\127\4\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\1\7"+
    "\1\130\1\7\1\0\1\7\1\0\7\7\1\0\7\7"+
    "\2\0\1\131\1\0\2\131\64\0\10\57\1\132\1\0"+
    "\1\61\57\57\11\62\1\0\1\63\1\133\56\62\11\65"+
    "\1\0\3\65\2\0\1\66\63\65\1\134\3\65\1\135"+
    "\1\0\1\66\52\65\11\136\1\137\2\136\1\67\2\137"+
    "\1\140\1\141\1\65\50\136\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\2\7\1\142\1\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\2\7\1\143\1\7"+
    "\2\0\2\7\1\144\1\0\1\7\1\0\7\7\1\0"+
    "\7\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\4\7\1\145"+
    "\2\7\1\0\7\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\1\7\1\146\1\7\1\0"+
    "\1\7\1\0\3\7\1\147\1\150\2\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\1\151\5\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\2\7\1\152\1\0\1\7\1\0"+
    "\7\7\1\0\7\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\1\7\1\153\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\0\7\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\1\154\5\7\1\0\7\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\1\155\6\7\1\0\7\7"+
    "\40\0\1\156\122\0\1\157\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\1\7\1\160\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\1\161\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\1\162\6\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\1\163"+
    "\1\164\2\7\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\7\7\47\0\1\165\24\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\2\7\1\166\1\0"+
    "\1\7\1\0\7\7\1\0\7\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\167\6\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\1\7"+
    "\1\170\1\7\1\0\1\7\1\0\7\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\2\7\1\171\4\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\2\7\1\172\1\0\1\7\1\0"+
    "\7\7\1\0\7\7\37\0\1\173\34\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\1\174\3\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\5\7\1\175\1\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\2\7\1\176\4\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\177\1\200\6\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\1\7\1\201\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\0\7\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\1\7\1\202\2\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\7\7\11\0"+
    "\1\134\60\0\11\65\1\0\2\65\1\203\2\0\1\66"+
    "\52\65\14\0\1\204\55\0\11\65\1\134\2\65\1\203"+
    "\1\135\1\0\1\66\52\65\11\203\1\204\3\203\2\204"+
    "\1\205\1\206\1\203\1\65\47\203\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\3\7\1\207\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\4\7\1\210\2\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\2\7\1\211\4\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\3\7\1\212\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\7\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\2\7\1\213\1\0\1\7"+
    "\1\0\7\7\1\0\7\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\2\7\1\214\4\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\2\7"+
    "\1\215\1\0\1\7\1\0\7\7\1\0\7\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\216\1\217\1\0\7\7\1\0\7\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\1\7\1\220\1\7\1\0\1\7\1\0\7\7\1\0"+
    "\7\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\5\7\1\221"+
    "\1\7\1\0\7\7\62\0\2\222\50\0\1\223\31\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\222\1\224\6\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\3\7"+
    "\1\225\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\7\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\1\7\1\226"+
    "\5\7\1\0\7\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\227\1\230\1\0"+
    "\7\7\1\0\7\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\1\7\1\231\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\0\7\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\5\7\1\232\1\7\1\0\7\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\2\7\1\233\1\0\1\7\1\0\7\7\1\0\7\7"+
    "\42\0\1\234\31\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\3\7\1\235\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\7\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\236\1\237\6\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\2\7\1\240\1\0"+
    "\1\7\1\0\7\7\1\0\7\7\37\0\1\241\34\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\1\242\3\7"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\7\1\243\5\7"+
    "\1\0\7\7\11\136\1\137\3\136\2\137\1\140\1\141"+
    "\1\65\50\136\20\137\1\244\1\0\50\137\11\136\1\245"+
    "\3\136\1\246\1\137\1\140\1\141\1\65\61\136\1\137"+
    "\3\136\2\137\1\247\1\141\1\65\50\136\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\4\7\1\250\2\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\0\2\7"+
    "\1\251\4\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\1\7\1\252\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\7\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\1\7\1\253\1\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7\42\0\1\254"+
    "\31\0\1\7\3\0\2\7\23\0\1\7\3\0\3\7"+
    "\1\255\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\7\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\4\7\1\256\2\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\1\257\3\7\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\7\7\53\0\1\260\73\0\1\261"+
    "\16\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\262\6\7\1\0"+
    "\7\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\2\7\1\263"+
    "\4\7\1\0\7\7\37\0\1\264\34\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\1\265\3\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\1\7"+
    "\1\266\1\7\1\0\1\7\1\0\7\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\1\7"+
    "\1\267\2\7\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\3\7\1\0\1\7\1\0\2\7"+
    "\1\270\4\7\1\0\7\7\60\0\1\271\13\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\5\7\1\272\1\7\1\0\7\7"+
    "\53\0\1\273\20\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\3\7\1\0\1\7\1\0\1\274"+
    "\6\7\1\0\7\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\3\7\1\275\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\7\7\42\0\1\276\31\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\3\7\1\277\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\7\7\17\204"+
    "\1\300\1\301\1\204\1\0\47\204\11\0\1\134\2\0"+
    "\1\204\57\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\3\7\1\302\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\3\7\1\303\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\7\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\1\304\5\7\1\0\7\7\2\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\3\7\1\305\3\7\1\0\7\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\3\7\1\306"+
    "\3\7\60\0\1\307\56\0\1\310\26\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\5\7\1\311\1\7\1\0\7\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\1\312\2\7\1\0\1\7\1\0\7\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\1\313"+
    "\3\7\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\7\7\2\0\1\7\3\0\2\7\23\0\1\7\3\0"+
    "\4\7\2\0\1\7\1\314\1\7\1\0\1\7\1\0"+
    "\7\7\1\0\7\7\2\0\1\7\3\0\2\7\23\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\0\1\7\1\0"+
    "\3\7\1\315\3\7\1\0\7\7\42\0\1\316\31\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\3\7\1\317"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\1\7\1\320\1\7\1\0\1\7\1\0\7\7"+
    "\1\0\7\7\47\0\1\321\24\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\2\7\1\322\1\0"+
    "\1\7\1\0\7\7\1\0\7\7\17\137\1\245\1\244"+
    "\1\0\50\137\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\1\7\1\323\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\7\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\1\7\1\324\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\3\7\1\325\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\7\7\2\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\6\7\1\326\1\0\7\7"+
    "\40\0\1\327\33\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\1\7\1\330\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\7\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\331\6\7\1\0\7\7\53\0\1\332\20\0"+
    "\1\7\3\0\2\7\23\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\1\333\6\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\3\7\1\334\3\7"+
    "\1\0\7\7\2\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\4\7\2\0\3\7\1\0\1\7\1\0\3\7"+
    "\1\335\3\7\1\0\7\7\2\0\1\7\3\0\2\7"+
    "\23\0\1\7\3\0\4\7\2\0\1\7\1\336\1\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7\2\0\1\7"+
    "\3\0\2\7\23\0\1\7\3\0\4\7\2\0\1\7"+
    "\1\337\1\7\1\0\1\7\1\0\7\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\340\1\341\1\0\7\7\1\0\7\7"+
    "\2\0\1\7\3\0\2\7\23\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\342\1\343\1\0\7\7\1\0\7\7"+
    "\42\0\1\344\31\0\1\7\3\0\2\7\23\0\1\7"+
    "\3\0\3\7\1\345\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\7\7\42\0\1\346\31\0\1\7\3\0"+
    "\2\7\23\0\1\7\3\0\3\7\1\347\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\7\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9280];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\1\11\2\1\1\11\2\1\1\11\2\1"+
    "\15\11\12\1\1\11\12\1\2\0\1\11\3\0\1\11"+
    "\3\0\5\1\3\11\4\1\2\0\4\1\1\0\7\1"+
    "\1\0\11\1\1\11\1\1\4\0\14\1\2\0\5\1"+
    "\1\11\5\1\1\0\3\1\1\0\3\1\2\0\1\1"+
    "\1\0\7\1\1\0\3\1\2\0\3\1\1\0\4\1"+
    "\1\0\1\1\1\0\2\1\1\0\2\1\1\0\7\1"+
    "\1\11\3\1\2\0\2\1\1\11\4\1\1\0\1\1"+
    "\1\11\5\1\1\0\5\1\2\11\5\1\1\0\2\1"+
    "\1\0\5\1\1\11\2\1\1\11\5\1\1\0\1\1"+
    "\1\0\1\1\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[231];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
  	yyline=1;
	yychar=1;
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 230) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.println("Este es un error lexico: "+yytext()+", en la linea: "+yyline+", en la columna: "+yychar);
            }
          case 60: break;
          case 2: 
            { 
            }
          case 61: break;
          case 3: 
            { return new Symbol(sym.ENTERO,yyline,yychar, yytext());
            }
          case 62: break;
          case 4: 
            { return new Symbol(sym.PNT,yyline,yychar, yytext());
            }
          case 63: break;
          case 5: 
            { return new Symbol(sym.ID,yyline,yychar, yytext());
            }
          case 64: break;
          case 6: 
            { yychar=1;
            }
          case 65: break;
          case 7: 
            { return new Symbol(sym.POR,yyline,yychar, yytext());
            }
          case 66: break;
          case 8: 
            { return new Symbol(sym.MAS,yyline,yychar, yytext());
            }
          case 67: break;
          case 9: 
            { return new Symbol(sym.PNTCOMA,yyline,yychar, yytext());
            }
          case 68: break;
          case 10: 
            { return new Symbol(sym.DSPUNTOS,yyline,yychar, yytext());
            }
          case 69: break;
          case 11: 
            { return new Symbol(sym.COMA,yyline,yychar, yytext());
            }
          case 70: break;
          case 12: 
            { return new Symbol(sym.PARIZQ,yyline,yychar, yytext());
            }
          case 71: break;
          case 13: 
            { return new Symbol(sym.PARDER,yyline,yychar, yytext());
            }
          case 72: break;
          case 14: 
            { return new Symbol(sym.LLAVEIZQ,yyline,yychar, yytext());
            }
          case 73: break;
          case 15: 
            { return new Symbol(sym.LLAVEDER,yyline,yychar, yytext());
            }
          case 74: break;
          case 16: 
            { return new Symbol(sym.MENOS,yyline,yychar, yytext());
            }
          case 75: break;
          case 17: 
            { return new Symbol(sym.DIVIDIDO,yyline,yychar, yytext());
            }
          case 76: break;
          case 18: 
            { return new Symbol(sym.MODULO,yyline,yychar, yytext());
            }
          case 77: break;
          case 19: 
            { return new Symbol(sym.POTENCIA,yyline,yychar, yytext());
            }
          case 78: break;
          case 20: 
            { return new Symbol(sym.MENOR,yyline,yychar, yytext());
            }
          case 79: break;
          case 21: 
            { return new Symbol(sym.MAYOR,yyline,yychar, yytext());
            }
          case 80: break;
          case 22: 
            { return new Symbol(sym.IGUAL,yyline,yychar, yytext());
            }
          case 81: break;
          case 23: 
            { return new Symbol(sym.CHAR,yyline,yychar, yytext());
            }
          case 82: break;
          case 24: 
            { return new Symbol(sym.CADENA,yyline,yychar, yytext());
            }
          case 83: break;
          case 25: 
            { return new Symbol(sym.DIFERENTE,yyline,yychar, yytext());
            }
          case 84: break;
          case 26: 
            { return new Symbol(sym.MENORIGUAL,yyline,yychar, yytext());
            }
          case 85: break;
          case 27: 
            { return new Symbol(sym.MAYORIGUAL,yyline,yychar, yytext());
            }
          case 86: break;
          case 28: 
            { return new Symbol(sym.OR,yyline,yychar, yytext());
            }
          case 87: break;
          case 29: 
            { return new Symbol(sym.OF,yyline,yychar, yytext());
            }
          case 88: break;
          case 30: 
            { return new Symbol(sym.DECIMAL,yyline,yychar, yytext());
            }
          case 89: break;
          case 31: 
            { return new Symbol(sym.END,yyline,yychar, yytext());
            }
          case 90: break;
          case 32: 
            { return new Symbol(sym.AND,yyline,yychar, yytext());
            }
          case 91: break;
          case 33: 
            { return new Symbol(sym.NOT,yyline,yychar, yytext());
            }
          case 92: break;
          case 34: 
            { return new Symbol(sym.NOR,yyline,yychar, yytext());
            }
          case 93: break;
          case 35: 
            { return new Symbol(sym.NIL,yyline,yychar, yytext());
            }
          case 94: break;
          case 36: 
            { return new Symbol(sym.VAR,yyline,yychar, yytext());
            }
          case 95: break;
          case 37: 
            { return new Symbol(sym.TRUE,yyline,yychar, yytext());
            }
          case 96: break;
          case 38: 
            { return new Symbol(sym.TYPE,yyline,yychar, yytext());
            }
          case 97: break;
          case 39: 
            { return new Symbol(sym.REAL,yyline,yychar, yytext());
            }
          case 98: break;
          case 40: 
            { return new Symbol(sym.NAND,yyline,yychar, yytext());
            }
          case 99: break;
          case 41: 
            { return new Symbol(sym.WORD,yyline,yychar, yytext());
            }
          case 100: break;
          case 42: 
            { return new Symbol(sym.FALSE,yyline,yychar, yytext());
            }
          case 101: break;
          case 43: 
            { return new Symbol(sym.ARRAY,yyline,yychar, yytext());
            }
          case 102: break;
          case 44: 
            { return new Symbol(sym.CONST,yyline,yychar, yytext());
            }
          case 103: break;
          case 45: 
            { return new Symbol(sym.BEGIN,yyline,yychar, yytext());
            }
          case 104: break;
          case 46: 
            { return new Symbol(sym.WRITE,yyline,yychar, yytext());
            }
          case 105: break;
          case 47: 
            { return new Symbol(sym.RECORD,yyline,yychar, yytext());
            }
          case 106: break;
          case 48: 
            { return new Symbol(sym.LENGTH,yyline,yychar, yytext());
            }
          case 107: break;
          case 49: 
            { return new Symbol(sym.STRING,yyline,yychar, yytext());
            }
          case 108: break;
          case 50: 
            { return new Symbol(sym.SIZEOF,yyline,yychar, yytext());
            }
          case 109: break;
          case 51: 
            { return new Symbol(sym.CHARAT,yyline,yychar, yytext());
            }
          case 110: break;
          case 52: 
            { return new Symbol(sym.MALLOC,yyline,yychar, yytext());
            }
          case 111: break;
          case 53: 
            { return new Symbol(sym.REPLACE,yyline,yychar, yytext());
            }
          case 112: break;
          case 54: 
            { return new Symbol(sym.PROGRAM,yyline,yychar, yytext());
            }
          case 113: break;
          case 55: 
            { return new Symbol(sym.INTEGER,yyline,yychar, yytext());
            }
          case 114: break;
          case 56: 
            { return new Symbol(sym.BOOLEAN,yyline,yychar, yytext());
            }
          case 115: break;
          case 57: 
            { return new Symbol(sym.WRITELN,yyline,yychar, yytext());
            }
          case 116: break;
          case 58: 
            { return new Symbol(sym.TOUPPERCASE,yyline,yychar, yytext());
            }
          case 117: break;
          case 59: 
            { return new Symbol(sym.TOLOWERCASE,yyline,yychar, yytext());
            }
          case 118: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
