/* The following code was generated by JFlex 1.6.1 */

package Pascal.Parser;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Lexico.flex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int TAG = 2;
  public static final int ATTR = 4;
  public static final int DOC = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1,  1,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\11\1\16\1\16\1\15\22\0\1\5\1\0\1\13"+
    "\1\22\1\21\1\33\1\0\1\10\1\27\1\30\1\20\1\23\1\26"+
    "\1\31\1\3\1\32\12\2\1\25\1\24\1\41\1\50\1\42\2\0"+
    "\1\44\1\62\1\54\1\52\1\40\1\43\1\56\1\64\1\61\2\6"+
    "\1\45\1\57\1\51\1\53\1\55\1\6\1\36\1\47\1\35\1\37"+
    "\1\66\1\63\1\6\1\65\1\6\1\0\1\12\1\0\1\34\1\7"+
    "\1\0\1\44\1\62\1\54\1\52\1\40\1\43\1\56\1\64\1\61"+
    "\2\6\1\45\1\57\1\51\1\53\1\55\1\6\1\36\1\47\1\35"+
    "\1\37\1\66\1\63\1\6\1\65\1\6\1\14\1\4\1\17\7\0"+
    "\1\16\252\0\2\60\115\0\1\46\u1ea8\0\1\16\1\16\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\2\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\3\5\1\22\1\23\2\5"+
    "\1\1\1\5\1\24\4\5\1\1\4\5\2\0\1\25"+
    "\3\0\1\26\3\0\4\5\1\27\1\30\1\31\2\5"+
    "\1\0\3\5\1\0\1\5\1\32\3\5\1\0\6\5"+
    "\1\33\1\25\1\26\2\2\4\0\3\5\1\34\1\5"+
    "\1\35\1\0\2\5\1\36\1\37\2\40\3\5\1\0"+
    "\3\5\1\0\2\5\1\41\2\0\1\2\1\0\1\42"+
    "\1\43\1\44\1\0\1\5\1\0\1\5\1\45\1\0"+
    "\1\5\1\25\1\5\1\0\1\5\1\0\2\5\1\0"+
    "\1\5\1\46\1\0\3\2\2\47\1\0\1\5\2\50"+
    "\2\5\1\0\1\5\2\51\1\5\2\52\1\2\1\0"+
    "\2\53\1\54\1\5\1\0\2\5\1\0\1\5\1\55"+
    "\2\56\1\57\2\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\67\0\156\0\245\0\67\0\334\0\u0113"+
    "\0\67\0\u014a\0\u0181\0\67\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\67\0\67\0\u01b8\0\u01ef"+
    "\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339\0\u0370\0\67"+
    "\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528"+
    "\0\u055f\0\u0596\0\u0113\0\67\0\u05cd\0\u014a\0\u0604\0\67"+
    "\0\u063b\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\67"+
    "\0\67\0\67\0\u07bc\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf"+
    "\0\u0906\0\u093d\0\334\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50"+
    "\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0596\0\u0113\0\u014a"+
    "\0\67\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4"+
    "\0\u0d1b\0\334\0\u0d52\0\334\0\u0d89\0\u0dc0\0\u0df7\0\334"+
    "\0\334\0\67\0\334\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a"+
    "\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\334\0\u1054\0\u108b"+
    "\0\u10c2\0\u10f9\0\334\0\334\0\334\0\u1130\0\u1167\0\u119e"+
    "\0\u11d5\0\334\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8\0\u131f"+
    "\0\u1356\0\u138d\0\u13c4\0\u13fb\0\u1432\0\334\0\u1469\0\u0c08"+
    "\0\u14a0\0\u0c3f\0\67\0\334\0\u14d7\0\u150e\0\67\0\334"+
    "\0\u1545\0\u157c\0\u15b3\0\u15ea\0\67\0\334\0\u1621\0\u1658"+
    "\0\u168f\0\u108b\0\u16c6\0\67\0\334\0\334\0\u16fd\0\u1734"+
    "\0\u176b\0\u17a2\0\u17d9\0\u1810\0\334\0\67\0\334\0\334"+
    "\0\67\0\334";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\3\1\4\1\7\1\3"+
    "\1\10\1\11\1\3\1\12\1\13\1\4\1\0\1\3"+
    "\1\14\2\3\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\7\1\31"+
    "\1\32\1\33\1\34\1\35\1\7\1\36\1\37\1\40"+
    "\1\41\1\7\1\42\1\43\1\44\2\7\1\45\1\46"+
    "\1\47\1\50\2\7\1\51\70\0\1\4\3\0\1\4"+
    "\7\0\1\4\53\0\1\5\1\52\65\0\1\7\3\0"+
    "\2\7\21\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\0\6\7\10\53\1\54\1\0"+
    "\1\55\54\53\11\56\1\0\1\57\1\60\53\56\11\61"+
    "\1\0\3\61\2\0\1\62\1\63\46\61\2\0\1\7"+
    "\3\0\2\7\21\0\1\7\3\0\1\7\1\64\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\0\4\7"+
    "\1\65\1\7\2\0\1\7\3\0\2\7\21\0\1\7"+
    "\3\0\3\7\1\66\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\2\0\1\7\3\0\2\7\21\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\67\6\7\1\0\6\7\42\0\1\70\5\0\1\71"+
    "\66\0\1\72\20\0\1\7\3\0\2\7\21\0\1\7"+
    "\3\0\4\7\2\0\1\7\1\73\1\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\21\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\74\6\7\1\0\6\7\35\0\1\75\33\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\1\76\3\7"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\0\6\7"+
    "\2\0\1\7\3\0\2\7\21\0\1\7\3\0\4\7"+
    "\2\0\1\7\1\77\1\7\1\0\1\7\1\0\2\7"+
    "\1\100\4\7\1\101\1\102\5\7\2\0\1\7\3\0"+
    "\2\7\21\0\1\7\3\0\1\7\1\103\2\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\6\7\2\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\2\7\1\104\4\7\1\0"+
    "\3\7\1\105\2\7\2\0\1\7\3\0\2\7\21\0"+
    "\1\7\3\0\1\7\1\106\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\0\6\7\51\0\1\107\17\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\1\110\6\7\1\0\6\7"+
    "\2\0\1\7\3\0\2\7\21\0\1\7\3\0\3\7"+
    "\1\111\2\0\3\7\1\0\1\7\1\0\2\7\1\112"+
    "\4\7\1\0\6\7\2\0\1\7\3\0\2\7\21\0"+
    "\1\7\3\0\1\7\1\113\2\7\2\0\3\7\1\0"+
    "\1\7\1\0\2\7\1\114\4\7\1\0\6\7\2\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\4\7\2\0"+
    "\1\7\1\115\1\7\1\0\1\7\1\0\7\7\1\0"+
    "\6\7\2\0\1\116\1\0\2\116\61\0\10\53\1\117"+
    "\1\0\1\55\54\53\11\56\1\0\1\57\1\120\53\56"+
    "\11\61\1\0\3\61\2\0\1\62\60\61\1\121\3\61"+
    "\1\122\1\0\1\62\47\61\11\123\1\124\2\123\1\63"+
    "\2\124\1\125\1\126\1\61\45\123\2\0\1\7\3\0"+
    "\2\7\21\0\1\7\3\0\2\7\1\127\1\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\6\7\2\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\4\7\1\130\2\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\4\7\2\0\1\7\1\131\1\7\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\2\0\1\7\3\0\2\7\21\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\0\1\7\1\0"+
    "\1\7\1\132\5\7\1\0\6\7\2\0\1\7\3\0"+
    "\2\7\21\0\1\7\3\0\4\7\2\0\2\7\1\133"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\2\0\1\7"+
    "\3\0\2\7\21\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\7\1\134\5\7\1\0\6\7"+
    "\36\0\1\135\32\0\1\7\3\0\2\7\21\0\1\7"+
    "\3\0\1\7\1\136\2\7\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\21\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\1\137\6\7\1\0\6\7\2\0\1\7\3\0"+
    "\2\7\21\0\1\7\3\0\1\140\1\141\2\7\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\6\7\45\0"+
    "\1\142\23\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\4\7\2\0\2\7\1\143\1\0\1\7\1\0\7\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\21\0\1\7"+
    "\3\0\4\7\2\0\3\7\1\0\1\7\1\0\1\144"+
    "\6\7\1\0\6\7\2\0\1\7\3\0\2\7\21\0"+
    "\1\7\3\0\4\7\2\0\1\7\1\145\1\7\1\0"+
    "\1\7\1\0\7\7\1\0\6\7\2\0\1\7\3\0"+
    "\2\7\21\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\2\7\1\146\4\7\1\0\6\7\35\0"+
    "\1\147\33\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\1\150\3\7\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\21\0\1\7"+
    "\3\0\4\7\2\0\3\7\1\0\1\7\1\0\5\7"+
    "\1\151\1\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\21\0\1\7\3\0\4\7\2\0\3\7\1\0\1\7"+
    "\1\0\2\7\1\152\4\7\1\0\6\7\2\0\1\7"+
    "\3\0\2\7\21\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\153\1\154\5\7\2\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\1\7\1\155"+
    "\2\7\2\0\3\7\1\0\1\7\1\0\7\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\1\7\1\156\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\11\0\1\121\55\0\11\61\1\0"+
    "\2\61\1\157\2\0\1\62\47\61\14\0\1\160\52\0"+
    "\11\61\1\121\2\61\1\157\1\122\1\0\1\62\47\61"+
    "\11\157\1\160\3\157\2\160\1\161\1\162\1\157\1\61"+
    "\44\157\2\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\3\7\1\163\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\21\0\1\7"+
    "\3\0\3\7\1\164\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\2\0\1\7\3\0\2\7\21\0"+
    "\1\7\3\0\4\7\2\0\2\7\1\165\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\21\0\1\7\3\0\4\7\2\0\3\7\1\166\1\167"+
    "\1\0\7\7\1\0\6\7\60\0\2\170\7\0\1\7"+
    "\3\0\2\7\21\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\170\1\171\5\7\2\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\1\7\1\172\5\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\173\1\174\1\0\7\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\1\7\1\175\2\7\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\2\0\1\7\3\0\2\7\21\0"+
    "\1\7\3\0\4\7\2\0\3\7\1\0\1\7\1\0"+
    "\5\7\1\176\1\7\1\0\6\7\40\0\1\177\30\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\3\7\1\200"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\0\6\7"+
    "\2\0\1\7\3\0\2\7\21\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\201\1\202"+
    "\5\7\2\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\4\7\2\0\2\7\1\203\1\0\1\7\1\0\7\7"+
    "\1\0\6\7\35\0\1\204\33\0\1\7\3\0\2\7"+
    "\21\0\1\7\3\0\1\205\3\7\2\0\3\7\1\0"+
    "\1\7\1\0\7\7\1\0\6\7\2\0\1\7\3\0"+
    "\2\7\21\0\1\7\3\0\4\7\2\0\3\7\1\0"+
    "\1\7\1\0\1\7\1\206\5\7\1\0\6\7\11\123"+
    "\1\124\3\123\2\124\1\125\1\126\1\61\45\123\20\124"+
    "\1\207\1\0\45\124\11\123\1\210\3\123\1\211\1\124"+
    "\1\125\1\126\1\61\56\123\1\124\3\123\2\124\1\212"+
    "\1\126\1\61\45\123\40\0\1\213\30\0\1\7\3\0"+
    "\2\7\21\0\1\7\3\0\3\7\1\214\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\51\0\1\215"+
    "\17\0\1\7\3\0\2\7\21\0\1\7\3\0\4\7"+
    "\2\0\3\7\1\0\1\7\1\0\1\216\6\7\1\0"+
    "\6\7\35\0\1\217\33\0\1\7\3\0\2\7\21\0"+
    "\1\7\3\0\1\220\3\7\2\0\3\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\2\0\1\7\3\0\2\7"+
    "\21\0\1\7\3\0\4\7\2\0\1\7\1\221\1\7"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\2\0\1\7"+
    "\3\0\2\7\21\0\1\7\3\0\1\7\1\222\2\7"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\0\6\7"+
    "\56\0\1\223\12\0\1\7\3\0\2\7\21\0\1\7"+
    "\3\0\4\7\2\0\3\7\1\0\1\7\1\0\5\7"+
    "\1\224\1\7\1\0\6\7\51\0\1\225\17\0\1\7"+
    "\3\0\2\7\21\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\226\6\7\1\0\6\7\2\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\3\7\1\227"+
    "\2\0\3\7\1\0\1\7\1\0\7\7\1\0\6\7"+
    "\40\0\1\230\30\0\1\7\3\0\2\7\21\0\1\7"+
    "\3\0\3\7\1\231\2\0\3\7\1\0\1\7\1\0"+
    "\7\7\1\0\6\7\17\160\1\232\1\233\1\160\1\0"+
    "\44\160\11\0\1\121\2\0\1\160\130\0\1\234\12\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\4\7\2\0"+
    "\3\7\1\0\1\7\1\0\5\7\1\235\1\7\1\0"+
    "\6\7\2\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\1\236\3\7\2\0\3\7\1\0\1\7\1\0\7\7"+
    "\1\0\6\7\2\0\1\7\3\0\2\7\21\0\1\7"+
    "\3\0\4\7\2\0\1\7\1\237\1\7\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\40\0\1\240\30\0\1\7"+
    "\3\0\2\7\21\0\1\7\3\0\3\7\1\241\2\0"+
    "\3\7\1\0\1\7\1\0\7\7\1\0\6\7\2\0"+
    "\1\7\3\0\2\7\21\0\1\7\3\0\4\7\2\0"+
    "\1\7\1\242\1\7\1\0\1\7\1\0\7\7\1\0"+
    "\6\7\45\0\1\243\23\0\1\7\3\0\2\7\21\0"+
    "\1\7\3\0\4\7\2\0\2\7\1\244\1\0\1\7"+
    "\1\0\7\7\1\0\6\7\17\124\1\210\1\207\1\0"+
    "\45\124\2\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\6\7\1\245"+
    "\1\0\6\7\36\0\1\246\32\0\1\7\3\0\2\7"+
    "\21\0\1\7\3\0\1\7\1\247\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\7\7\1\0\6\7\2\0\1\7"+
    "\3\0\2\7\21\0\1\7\3\0\4\7\2\0\3\7"+
    "\1\0\1\7\1\0\1\250\6\7\1\0\6\7\51\0"+
    "\1\251\17\0\1\7\3\0\2\7\21\0\1\7\3\0"+
    "\4\7\2\0\3\7\1\0\1\7\1\0\1\252\6\7"+
    "\1\0\6\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6215];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\1\11\2\1\1\11\2\1\1\11\2\1"+
    "\13\11\11\1\1\11\11\1\2\0\1\11\3\0\1\11"+
    "\3\0\4\1\3\11\2\1\1\0\3\1\1\0\5\1"+
    "\1\0\11\1\1\11\1\1\4\0\6\1\1\0\4\1"+
    "\1\11\4\1\1\0\3\1\1\0\3\1\2\0\1\1"+
    "\1\0\3\1\1\0\1\1\1\0\2\1\1\0\3\1"+
    "\1\0\1\1\1\0\2\1\1\0\2\1\1\0\3\1"+
    "\1\11\1\1\1\0\1\1\1\11\3\1\1\0\1\1"+
    "\1\11\5\1\1\0\1\11\3\1\1\0\2\1\1\0"+
    "\2\1\1\11\2\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
  	yyline=1;
	yychar=1;
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 230) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.println("Este es un error lexico: "+yytext()+", en la linea: "+yyline+", en la columna: "+yychar);
            }
          case 49: break;
          case 2: 
            { 
            }
          case 50: break;
          case 3: 
            { return new Symbol(sym.ENTERO,yyline,yychar, yytext());
            }
          case 51: break;
          case 4: 
            { return new Symbol(sym.PNT,yyline,yychar, yytext());
            }
          case 52: break;
          case 5: 
            { return new Symbol(sym.ID,yyline,yychar, yytext());
            }
          case 53: break;
          case 6: 
            { yychar=1;
            }
          case 54: break;
          case 7: 
            { return new Symbol(sym.POR,yyline,yychar, yytext());
            }
          case 55: break;
          case 8: 
            { return new Symbol(sym.MAS,yyline,yychar, yytext());
            }
          case 56: break;
          case 9: 
            { return new Symbol(sym.PNTCOMA,yyline,yychar, yytext());
            }
          case 57: break;
          case 10: 
            { return new Symbol(sym.DSPUNTOS,yyline,yychar, yytext());
            }
          case 58: break;
          case 11: 
            { return new Symbol(sym.COMA,yyline,yychar, yytext());
            }
          case 59: break;
          case 12: 
            { return new Symbol(sym.PARIZQ,yyline,yychar, yytext());
            }
          case 60: break;
          case 13: 
            { return new Symbol(sym.PARDER,yyline,yychar, yytext());
            }
          case 61: break;
          case 14: 
            { return new Symbol(sym.MENOS,yyline,yychar, yytext());
            }
          case 62: break;
          case 15: 
            { return new Symbol(sym.DIVIDIDO,yyline,yychar, yytext());
            }
          case 63: break;
          case 16: 
            { return new Symbol(sym.MODULO,yyline,yychar, yytext());
            }
          case 64: break;
          case 17: 
            { return new Symbol(sym.POTENCIA,yyline,yychar, yytext());
            }
          case 65: break;
          case 18: 
            { return new Symbol(sym.MENOR,yyline,yychar, yytext());
            }
          case 66: break;
          case 19: 
            { return new Symbol(sym.MAYOR,yyline,yychar, yytext());
            }
          case 67: break;
          case 20: 
            { return new Symbol(sym.IGUAL,yyline,yychar, yytext());
            }
          case 68: break;
          case 21: 
            { return new Symbol(sym.CHAR,yyline,yychar, yytext());
            }
          case 69: break;
          case 22: 
            { return new Symbol(sym.CADENA,yyline,yychar, yytext());
            }
          case 70: break;
          case 23: 
            { return new Symbol(sym.DIFERENTE,yyline,yychar, yytext());
            }
          case 71: break;
          case 24: 
            { return new Symbol(sym.MENORIGUAL,yyline,yychar, yytext());
            }
          case 72: break;
          case 25: 
            { return new Symbol(sym.MAYORIGUAL,yyline,yychar, yytext());
            }
          case 73: break;
          case 26: 
            { return new Symbol(sym.OR,yyline,yychar, yytext());
            }
          case 74: break;
          case 27: 
            { return new Symbol(sym.DECIMAL,yyline,yychar, yytext());
            }
          case 75: break;
          case 28: 
            { return new Symbol(sym.END,yyline,yychar, yytext());
            }
          case 76: break;
          case 29: 
            { return new Symbol(sym.AND,yyline,yychar, yytext());
            }
          case 77: break;
          case 30: 
            { return new Symbol(sym.NOT,yyline,yychar, yytext());
            }
          case 78: break;
          case 31: 
            { return new Symbol(sym.NOR,yyline,yychar, yytext());
            }
          case 79: break;
          case 32: 
            { return new Symbol(sym.NIL,yyline,yychar, yytext());
            }
          case 80: break;
          case 33: 
            { return new Symbol(sym.VAR,yyline,yychar, yytext());
            }
          case 81: break;
          case 34: 
            { return new Symbol(sym.TRUE,yyline,yychar, yytext());
            }
          case 82: break;
          case 35: 
            { return new Symbol(sym.TYPE,yyline,yychar, yytext());
            }
          case 83: break;
          case 36: 
            { return new Symbol(sym.REAL,yyline,yychar, yytext());
            }
          case 84: break;
          case 37: 
            { return new Symbol(sym.NAND,yyline,yychar, yytext());
            }
          case 85: break;
          case 38: 
            { return new Symbol(sym.WORD,yyline,yychar, yytext());
            }
          case 86: break;
          case 39: 
            { return new Symbol(sym.FALSE,yyline,yychar, yytext());
            }
          case 87: break;
          case 40: 
            { return new Symbol(sym.CONST,yyline,yychar, yytext());
            }
          case 88: break;
          case 41: 
            { return new Symbol(sym.BEGIN,yyline,yychar, yytext());
            }
          case 89: break;
          case 42: 
            { return new Symbol(sym.WRITE,yyline,yychar, yytext());
            }
          case 90: break;
          case 43: 
            { return new Symbol(sym.STRING,yyline,yychar, yytext());
            }
          case 91: break;
          case 44: 
            { return new Symbol(sym.CHARAT,yyline,yychar, yytext());
            }
          case 92: break;
          case 45: 
            { return new Symbol(sym.PROGRAM,yyline,yychar, yytext());
            }
          case 93: break;
          case 46: 
            { return new Symbol(sym.INTEGER,yyline,yychar, yytext());
            }
          case 94: break;
          case 47: 
            { return new Symbol(sym.BOOLEAN,yyline,yychar, yytext());
            }
          case 95: break;
          case 48: 
            { return new Symbol(sym.WRITELN,yyline,yychar, yytext());
            }
          case 96: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
