
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Pascal.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 12;
  public static final int DECIMAL = 10;
  public static final int MENOS = 4;
  public static final int UMENOS = 2;
  public static final int ENTERO = 9;
  public static final int POR = 5;
  public static final int DIVIDIDO = 6;
  public static final int SALUDO = 7;
  public static final int EOF = 0;
  public static final int MAS = 3;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int CHAR = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UMENOS",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "SALUDO",
  "ID",
  "ENTERO",
  "DECIMAL",
  "CHAR",
  "CADENA"
  };
}

